import CryptoKit
import Foundation
import os
import WorkshopCore
import WorkshopStore

/// Single-writer collaboration service: owns the database, adapter registry,
/// outbox dispatch and recovery (spec §4.3, §5.2, §9.4).
public actor CollaborationService {
    public static let dispatchRequested = "dispatch.requested"

    private let repo: WorkshopRepository
    private var adapters: [EngineerID: EngineerAdapter]
    private let now: () -> Date
    private let dispatcherEnabled: Bool
    private var dispatcherScheduled = false
    private var inflightTurns = 0
    private var eventContinuations: [UUID: AsyncStream<OutboxEvent>.Continuation] = [:]
    private var lastPublishedSeq: Int64 = 0
    private var isShutdown = false

    /// Workshop home dir (tokens, artifacts, worktrees); nil in bare tests.
    public let homeDir: String?
    /// Wakeup batching interval (§5.4); 0 in tests.
    private let wakeupCoalescence: Duration
    /// Max consecutive engineer-triggered wakeups without a user message (T11).
    private let wakeupLoopBound: Int
    private var wakeupScheduled = false
    /// (task, engineer) pairs with a turn currently running.
    private var runningTurns: Set<String> = []

    /// Test hook: called with the rendered context packet before each sendTurn.
    public var packetInspector: (@Sendable (EngineerID, String) -> Void)?

    public func setPacketInspector(_ f: (@Sendable (EngineerID, String) -> Void)?) {
        packetInspector = f
    }

    private let log = Logger(subsystem: "ai.maapu.workshop", category: "service")

    /// Run a repo/db mutation, logging failures instead of silently swallowing them.
    private func attempt<T>(_ label: String, _ body: () throws -> T) -> T? {
        do { return try body() } catch {
            log.error("\(label, privacy: .public) failed: \(error.localizedDescription, privacy: .public)")
            return nil
        }
    }

    public init(database: Database, adapters: [EngineerAdapter],
                dispatcherEnabled: Bool = true,
                homeDir: String? = nil,
                wakeupCoalescence: Duration = .milliseconds(500),
                wakeupLoopBound: Int = 6,
                now: @escaping () -> Date = Date.init) throws {
        try Migrations.all.migrate(database)
        self.repo = WorkshopRepository(db: database)
        self.adapters = Dictionary(uniqueKeysWithValues: adapters.map { ($0.engineer, $0) })
        self.dispatcherEnabled = dispatcherEnabled
        self.homeDir = homeDir
        self.wakeupCoalescence = wakeupCoalescence
        self.wakeupLoopBound = wakeupLoopBound
        self.now = now
    }

    public convenience init(databasePath: String, adapters: [EngineerAdapter],
                            dispatcherEnabled: Bool = true,
                            homeDir: String? = nil,
                            wakeupCoalescence: Duration = .milliseconds(500),
                            wakeupLoopBound: Int = 6,
                            now: @escaping () -> Date = Date.init) throws {
        try self.init(database: try Database(path: databasePath), adapters: adapters,
                      dispatcherEnabled: dispatcherEnabled, homeDir: homeDir,
                      wakeupCoalescence: wakeupCoalescence,
                      wakeupLoopBound: wakeupLoopBound, now: now)
    }

    // MARK: - Authentication

    /// Resolve a capability token to an engineer principal (spec §9.3). Tokens are
    /// 32-byte hex files at <home>/profiles/<engineer>/token generated by the daemon.
    public func authenticate(token: String) throws -> Principal {
        guard let homeDir else { throw WorkshopError.invalidRequest("no token store") }
        for engineer in EngineerID.allCases {
            let path = homeDir + "/profiles/" + engineer.rawValue + "/token"
            guard let stored = try? String(contentsOfFile: path, encoding: .utf8)
                .trimmingCharacters(in: .whitespacesAndNewlines),
                  !stored.isEmpty, stored == token else { continue }
            return .engineer(engineer)
        }
        throw WorkshopError.invalidRequest("invalid token")
    }

    /// Recovery, then process any pending dispatch rows exactly once (T03).
    public func start() async {
        recoverInterruptedStreams()
        scheduleDispatch()
    }

    /// Replace an adapter after init (e.g. binding a live adapter's tool
    /// executor to this service). Used at daemon startup.
    public func registerAdapter(_ adapter: EngineerAdapter) {
        adapters[adapter.engineer] = adapter
    }

    public func shutdown() {
        isShutdown = true
        for continuation in eventContinuations.values { continuation.finish() }
        eventContinuations.removeAll()
    }

    /// Wait until the dispatcher has no pending work. For tests.
    public func awaitIdle() async {
        while dispatcherScheduled || inflightTurns > 0 {
            try? await Task.sleep(for: .milliseconds(5))
        }
        if let pending = attempt("pendingOutbox", { try repo.pendingOutbox(eventType: Self.dispatchRequested) }),
           !pending.isEmpty, dispatcherEnabled, !isShutdown {
            scheduleDispatch()
            while dispatcherScheduled || inflightTurns > 0 {
                try? await Task.sleep(for: .milliseconds(5))
            }
        }
    }

    // MARK: - Event broadcast

    /// In-process stream of committed outbox events (plus transient message.delta events).
    public func makeEventStream() -> AsyncStream<OutboxEvent> {
        let id = UUID()
        return AsyncStream { continuation in
            eventContinuations[id] = continuation
            continuation.onTermination = { [weak self] _ in
                Task { await self?.removeContinuation(id) }
            }
        }
    }

    private func removeContinuation(_ id: UUID) {
        eventContinuations.removeValue(forKey: id)
    }

    private func publishCommitted() {
        guard let rows = attempt("outboxEvents", { try repo.outboxEvents(afterSeq: lastPublishedSeq) }) else { return }
        for row in rows {
            lastPublishedSeq = max(lastPublishedSeq, row.seq)
            for continuation in eventContinuations.values {
                continuation.yield(row)
            }
        }
    }

    private func publishTransient(taskID: TaskID, type: String, payload: String) {
        let event = OutboxEvent(seq: lastPublishedSeq, taskID: taskID, eventType: type,
                                payload: payload, deliveryState: "transient",
                                createdAt: now())
        for continuation in eventContinuations.values {
            continuation.yield(event)
        }
    }

    // MARK: - Queries

    public func listTasks() throws -> [WorkshopTask] {
        try repo.listTasks()
    }

    public func getTask(_ id: TaskID) throws -> TaskDetail {
        guard let task = try repo.task(id) else { throw WorkshopError.taskNotFound(id) }
        var usage = try repo.latestUsage(id)
        if usage == nil,
           let event = try repo.latestOutboxEvent(taskID: id, eventType: "task.state_changed"),
           let payload = try? JSONDecoder().decode(StateChangedPayload.self,
                                                   from: Data(event.payload.utf8)) {
            usage = payload.usage
        }
        let running = runningTurns
            .filter { $0.hasPrefix(id.rawValue + ":") }
            .compactMap { EngineerID(rawValue: String($0.split(separator: ":")[1])) }
        let wakeups = (try repo.wakeups(id))
            .filter { $0.state == "pending" || $0.state == "running" }
            .map { WakeupInfo(engineer: $0.engineerID, reason: $0.reason,
                              state: $0.state) }
        return TaskDetail(task: task,
                          participants: try repo.participants(id),
                          subtasks: try repo.subtasks(id),
                          usage: usage,
                          runningEngineers: running,
                          pendingWakeups: wakeups)
    }

    /// Artifact rows for a task (workshop.listArtifacts).
    public func listArtifacts(_ taskID: TaskID) throws -> [Artifact] {
        try repo.artifacts(taskID)
    }

    /// All usage samples for a task (workshop.listUsage).
    public func listUsage(_ taskID: TaskID) throws -> [UsageSampleRecord] {
        try repo.usageSamples(taskID)
    }

    public func readMessages(_ taskID: TaskID, afterSeq: Int64 = 0, limit: Int = 500) throws -> [Message] {
        try repo.messages(taskID, afterSeq: afterSeq, limit: limit)
    }

    public func listEngineers() async -> [AdapterProbe] {
        var probes: [AdapterProbe] = []
        for engineer in EngineerID.allCases {
            if let adapter = adapters[engineer] {
                probes.append(await adapter.probe())
            } else {
                probes.append(AdapterProbe(engineer: engineer,
                                           health: .unavailable("adapter not configured")))
            }
        }
        return probes
    }

    public func outboxEvents(afterSeq: Int64) throws -> [OutboxEvent] {
        try repo.outboxEvents(afterSeq: afterSeq)
    }

    // MARK: - Commands

    /// Create a task: idempotent on `idempotency_key`; single commit for task + root
    /// message + participants + root subtask + outbox (spec §8.4/§8.5, T01/T02).
    public func createTask(_ request: CreateTaskRequest) throws -> CreateTaskReceipt {
        guard !request.title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw WorkshopError.invalidRequest("title must not be empty")
        }
        guard !request.objective.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw WorkshopError.invalidRequest("objective must not be empty")
        }
        let payloadHash = try canonicalJSONHash(of: request)

        if let existing = try repo.operation(request.idempotencyKey) {
            if existing.payloadHash == payloadHash {
                let data = Data(existing.resultJSON.utf8)
                return try JSONDecoder().decode(CreateTaskReceipt.self, from: data)
            }
            throw WorkshopError.idempotencyConflict
        }

        let timestamp = now()
        let taskID = TaskID(newID("task"))
        let messageID = MessageID(newID("msg"))
        let subtaskID = SubtaskID(newID("sub"))

        let task = WorkshopTask(id: taskID, channel: request.channel, title: request.title,
                                brief: request.objective, phase: request.phase,
                                state: .queued, budgetPolicyRef: request.budgetPolicyRef,
                                createdAt: timestamp, updatedAt: timestamp)
        let rootMessage = Message(id: messageID, taskID: taskID, seq: 1, author: .user,
                                  kind: .text, body: request.objective,
                                  deliveryState: .committed,
                                  createdAt: timestamp, updatedAt: timestamp)
        let rootSubtask = Subtask(id: subtaskID, taskID: taskID, title: request.title,
                                  acceptance: request.acceptanceCriteria,
                                  state: .ready, createdAt: timestamp, updatedAt: timestamp)

        var receipt: CreateTaskReceipt?
        try repo.db.transaction {
            try repo.insertTask(task)
            try repo.insertMessage(rootMessage)
            for engineer in request.participants {
                try repo.insertParticipant(Participant(taskID: taskID, engineerID: engineer))
            }
            try repo.insertSubtask(rootSubtask)
            var seq = try repo.insertOutbox(
                taskID: taskID, eventType: "task.created",
                payload: #"{"task_id":""# + taskID.rawValue + #""}"#,
                deliveryState: "pending", at: timestamp)
            switch request.phase {
            case .execution, .followUp:
                seq = try repo.insertOutbox(
                    taskID: taskID, eventType: Self.dispatchRequested,
                    payload: #"{"task_id":""# + taskID.rawValue
                        + #"","subtask_id":""# + subtaskID.rawValue + #""}"#,
                    deliveryState: "pending", at: timestamp)
            case .researchProposal:
                try repo.insertMessage(Message(
                    id: MessageID(newID("msg")), taskID: taskID,
                    seq: try repo.nextMessageSeq(taskID), author: .system,
                    kind: .systemEvent,
                    body: "Research/proposal phase requires the Phase 3 collaboration "
                        + "policy, which is not yet implemented. Task preserved in Queued.",
                    deliveryState: .committed, createdAt: timestamp, updatedAt: timestamp))
            }
            let r = CreateTaskReceipt(taskID: taskID, committedSeq: seq, state: .queued,
                                      status: .created, deepLink: nil)
            let receiptJSON = String(data: try JSONEncoder().encode(r), encoding: .utf8)!
            try repo.insertOperation(key: request.idempotencyKey, principal: "user",
                                     payloadHash: payloadHash, resultJSON: receiptJSON,
                                     at: timestamp)
            receipt = r
        }
        publishCommitted()
        scheduleDispatch()
        return receipt!
    }

    /// Append a message to an existing task; author identity comes from the
    /// connection principal, never from caller params (§9.3).
    @discardableResult
    public func postMessage(taskID: TaskID, body: String, principal: Principal = .user,
                            kind: MessageKind = .text, replyTo: MessageID? = nil,
                            structured: String? = nil) throws -> Message {
        guard try repo.task(taskID) != nil else { throw WorkshopError.taskNotFound(taskID) }
        if let engineer = principal.engineerID {
            try requireParticipant(engineer, taskID: taskID)
        }
        let timestamp = now()
        let messageID = MessageID(newID("msg"))
        var committed: Message?
        try repo.db.transaction {
            let m = Message(id: messageID, taskID: taskID, seq: try repo.nextMessageSeq(taskID),
                            author: principal, kind: kind, body: body, replyTo: replyTo,
                            deliveryState: .committed, structured: structured,
                            createdAt: timestamp, updatedAt: timestamp)
            try repo.insertMessage(m)
            committed = m
            try repo.insertOutbox(taskID: taskID, eventType: "message.committed",
                                  payload: #"{"message_id":""# + m.id.rawValue
                                      + #"","task_id":""# + taskID.rawValue + #""}"#,
                                  deliveryState: "pending", at: timestamp)
            try enqueueWakeups(for: m, at: timestamp)
        }
        publishCommitted()
        scheduleWakeupCoalescer()
        return committed!
    }

    private func requireParticipant(_ engineer: EngineerID, taskID: TaskID) throws {
        guard try repo.participant(taskID, engineer) != nil else {
            throw WorkshopError.notAParticipant(engineer: engineer, task: taskID)
        }
    }

    // MARK: - Collaboration tools (spec §8.3)

    /// workshop_get_task for an engineer principal.
    public func toolGetTask(taskID: TaskID, principal: Principal) throws -> TaskDetail {
        if let engineer = principal.engineerID {
            try requireParticipant(engineer, taskID: taskID)
        }
        return try getTask(taskID)
    }

    /// workshop_read_messages for an engineer principal.
    public func toolReadMessages(taskID: TaskID, afterSeq: Int64, limit: Int,
                                 principal: Principal) throws -> [Message] {
        if let engineer = principal.engineerID {
            try requireParticipant(engineer, taskID: taskID)
        }
        return try repo.messages(taskID, afterSeq: afterSeq, limit: limit)
    }

    /// workshop_post_message: kind text|proposal|review|help_request|decision;
    /// help_request posts as text with a structured flag.
    public func toolPostMessage(taskID: TaskID, body: String, kind: String,
                                replyTo: MessageID?, principal: Principal) throws -> Message {
        let messageKind: MessageKind
        var structured: String?
        switch kind {
        case "help_request":
            messageKind = .text
            structured = #"{"help_request":true}"#
        case let raw:
            guard let parsed = MessageKind(rawValue: raw), parsed != .systemEvent else {
                throw WorkshopError.invalidRequest("unsupported kind: \(raw)")
            }
            messageKind = parsed
        }
        return try postMessage(taskID: taskID, body: body, principal: principal,
                               kind: messageKind, replyTo: replyTo, structured: structured)
    }

    /// workshop_request_review: posts a review-request message and wakes the target.
    public func toolRequestReview(taskID: TaskID, reviewer: EngineerID, message: String,
                                  principal: Principal) throws -> Message {
        if let engineer = principal.engineerID {
            try requireParticipant(engineer, taskID: taskID)
        }
        guard try repo.participant(taskID, reviewer) != nil else {
            throw WorkshopError.invalidRequest("reviewer is not a participant")
        }
        let structured = String(
            decoding: try JSONEncoder().encode(["reviewer": reviewer.rawValue]),
            as: UTF8.self)
        return try postMessage(taskID: taskID,
                               body: "@\(reviewer.rawValue) \(message)",
                               principal: principal, kind: .review, structured: structured)
    }

    /// workshop_get_capacity: every bucket unknown in this phase (§10.1).
    public func toolGetCapacity() -> JSONValue {
        .object(EngineerID.allCases.reduce(into: [String: JSONValue]()) { acc, e in
            acc[e.rawValue] = .object([
                "remaining": .string("unknown"),
                "source": .string("not measured"),
                "freshness": .null,
            ])
        })
    }

    /// workshop_save_checkpoint: stores a §6.3 checkpoint document.
    public func toolSaveCheckpoint(taskID: TaskID, content: JSONValue,
                                   principal: Principal) throws -> JSONValue {
        guard let engineer = principal.engineerID else {
            throw WorkshopError.invalidRequest("checkpoints require an engineer principal")
        }
        try requireParticipant(engineer, taskID: taskID)
        let generation = Int(content["ownership_generation"]?.intValue ?? 0)
        let schemaVersion = Int(content["schema_version"]?.intValue ?? 1)
        let data = try JSONEncoder().encode(content)
        let id = try repo.insertCheckpoint(taskID: taskID, engineerID: engineer,
                                           role: "main", workerID: "main",
                                           generation: generation,
                                           schemaVersion: schemaVersion,
                                           content: String(decoding: data, as: UTF8.self),
                                           at: now())
        return .object(["checkpoint_id": .number(Double(id))])
    }

    /// workshop_report_result: owner submits evidence; subtask → review, task → verifying.
    public func toolReportResult(taskID: TaskID, subtaskID: SubtaskID, summary: String,
                                 artifactIDs: [String], validation: [JSONValue],
                                 principal: Principal) throws -> Message {
        guard let engineer = principal.engineerID else {
            throw WorkshopError.invalidRequest("report_result requires an engineer principal")
        }
        try requireParticipant(engineer, taskID: taskID)
        guard let subtask = try repo.subtask(subtaskID), subtask.taskID == taskID,
              subtask.ownerID == engineer else {
            throw WorkshopError.notOwner
        }
        let timestamp = now()
        let structured = String(
            decoding: try JSONEncoder().encode(JSONValue.object([
                "subtask_id": .string(subtaskID.rawValue),
                "generation": .number(Double(subtask.generation)),
                "artifact_ids": .array(artifactIDs.map { .string($0) }),
                "validation": .array(validation),
            ])), as: UTF8.self)
        var committed: Message?
        try repo.db.transaction {
            let m = Message(id: MessageID(newID("msg")), taskID: taskID,
                            seq: try repo.nextMessageSeq(taskID), author: principal,
                            kind: .text, body: summary, deliveryState: .committed,
                            structured: structured, createdAt: timestamp, updatedAt: timestamp)
            try repo.insertMessage(m)
            committed = m
            try repo.updateSubtaskState(subtaskID, .review, at: timestamp)
            if let task = try repo.task(taskID), task.state == .working {
                try transition(taskID, from: .working, to: .verifying, at: timestamp)
            }
            try repo.insertMessage(Message(
                id: MessageID(newID("msg")), taskID: taskID,
                seq: try repo.nextMessageSeq(taskID), author: .system,
                kind: .systemEvent, body: "Owner reported complete; verification pending",
                deliveryState: .committed, createdAt: timestamp, updatedAt: timestamp))
            try repo.insertOutbox(taskID: taskID, eventType: "message.committed",
                                  payload: #"{"message_id":""# + m.id.rawValue
                                      + #"","task_id":""# + taskID.rawValue + #""}"#,
                                  deliveryState: "pending", at: timestamp)
        }
        publishCommitted()
        return committed!
    }

    /// workshop_publish_artifact: copy a workspace file into the artifact store with
    /// content-hash naming; path must resolve inside the task worktree (T26).
    public func toolPublishArtifact(taskID: TaskID, path: String, description: String?,
                                    principal: Principal) throws -> Artifact {
        guard let engineer = principal.engineerID else {
            throw WorkshopError.invalidRequest("publish_artifact requires an engineer principal")
        }
        try requireParticipant(engineer, taskID: taskID)
        guard let homeDir else {
            throw WorkshopError.invalidRequest("no artifact store configured")
        }
        let workspace = try WorkspaceManager.worktreePath(homeDir: homeDir, taskID: taskID)
        let source = try WorkspaceManager.resolveInsideWorkspace(workspace, path)
        let data = try Data(contentsOf: URL(fileURLWithPath: source))
        let hash = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        let artifactID = "art_" + UUID().uuidString.lowercased()
        let baseName = (source as NSString).lastPathComponent
        let destDir = homeDir + "/artifacts/" + taskID.rawValue
        let dest = destDir + "/" + String(hash.prefix(16)) + "-" + baseName
        try FileManager.default.createDirectory(atPath: destDir, withIntermediateDirectories: true)
        // Write via temp + fsync + rename for crash safety.
        let tmp = destDir + "/.tmp-" + artifactID
        try data.write(to: URL(fileURLWithPath: tmp), options: .atomic)
        let fh = try FileHandle(forWritingTo: URL(fileURLWithPath: tmp))
        try fh.synchronize(); try fh.close()
        if FileManager.default.fileExists(atPath: dest) {
            try FileManager.default.removeItem(atPath: tmp)
        } else {
            try FileManager.default.moveItem(atPath: tmp, toPath: dest)
        }
        let artifact = Artifact(id: artifactID, taskID: taskID, contentHash: hash,
                                relativePath: "artifacts/\(taskID.rawValue)/\(String(hash.prefix(16)))-\(baseName)",
                                producer: engineer.rawValue, description: description,
                                createdAt: now())
        try repo.db.transaction { try repo.insertArtifact(artifact) }
        return artifact
    }

    /// Unified entry point for the §8.3 collaboration tools — used by the IPC
    /// daemon, the workshop-mcp bridge, and the DeepSeek tool loop. Author
    /// identity always comes from `principal`, never from args.
    public func callTool(_ name: String, args: JSONValue,
                         principal: Principal) async throws -> JSONValue {
        switch name {
        case "workshop_get_task":
            let id = TaskID(args["task_id"]?.stringValue ?? "")
            return try .from(try toolGetTask(taskID: id, principal: principal))
        case "workshop_read_messages":
            let id = TaskID(args["task_id"]?.stringValue ?? "")
            return try .from(try toolReadMessages(
                taskID: id, afterSeq: args["after_seq"]?.intValue ?? 0,
                limit: Int(args["limit"]?.intValue ?? 200), principal: principal))
        case "workshop_post_message":
            let id = TaskID(args["task_id"]?.stringValue ?? "")
            guard let body = args["body"]?.stringValue else {
                throw WorkshopError.invalidRequest("body required")
            }
            return try .from(try toolPostMessage(
                taskID: id, body: body, kind: args["kind"]?.stringValue ?? "text",
                replyTo: args["reply_to"]?.stringValue.map { MessageID($0) },
                principal: principal))
        case "workshop_request_review":
            let id = TaskID(args["task_id"]?.stringValue ?? "")
            guard let reviewerRaw = args["reviewer"]?.stringValue,
                  let reviewer = EngineerID(rawValue: reviewerRaw),
                  let message = args["message"]?.stringValue else {
                throw WorkshopError.invalidRequest("reviewer and message required")
            }
            return try .from(try toolRequestReview(taskID: id, reviewer: reviewer,
                                                   message: message, principal: principal))
        case "workshop_publish_artifact":
            let id = TaskID(args["task_id"]?.stringValue ?? "")
            guard let path = args["path"]?.stringValue else {
                throw WorkshopError.invalidRequest("path required")
            }
            return try .from(try toolPublishArtifact(
                taskID: id, path: path,
                description: args["description"]?.stringValue, principal: principal))
        case "workshop_report_result":
            let id = TaskID(args["task_id"]?.stringValue ?? "")
            let subtaskID = SubtaskID(args["subtask_id"]?.stringValue ?? "")
            guard let summary = args["summary"]?.stringValue else {
                throw WorkshopError.invalidRequest("summary required")
            }
            return try .from(try toolReportResult(
                taskID: id, subtaskID: subtaskID, summary: summary,
                artifactIDs: args["artifact_ids"]?.arrayValue?
                    .compactMap { $0.stringValue } ?? [],
                validation: args["validation"]?.arrayValue ?? [],
                principal: principal))
        case "workshop_get_capacity":
            return toolGetCapacity()
        case "workshop_save_checkpoint":
            let id = TaskID(args["task_id"]?.stringValue ?? "")
            var content = args
            if case .object(var obj) = content {
                obj.removeValue(forKey: "task_id")
                content = .object(obj)
            }
            return try toolSaveCheckpoint(taskID: id, content: content, principal: principal)
        case "workshop_create_task", "workshop_propose_subtask",
             "workshop_claim_subtask", "workshop_assign_subtask":
            throw WorkshopError.phaseNotImplemented(name)
        default:
            throw WorkshopError.methodNotFound(name)
        }
    }

    // MARK: - Wakeups (§5.4)

    /// Compute wakeup targets for a committed message and insert pending rows.
    /// Must be called inside the committing transaction.
    private func enqueueWakeups(for message: Message, at timestamp: Date) throws {
        let participants = try repo.participants(message.taskID)
        let participantIDs = Set(participants.map(\.engineerID))
        var targets: [(EngineerID, String)] = []

        switch message.author {
        case .system:
            return // system events never wake anyone
        case .user:
            // A user reply wakes the current owner (T10).
            if let owner = try repo.subtasks(message.taskID).lazy
                .compactMap(\.ownerID).first, participantIDs.contains(owner) {
                targets.append((owner, "user_message"))
            }
        case .engineer(let author):
            // Explicit @mentions of other participants.
            for engineer in EngineerID.allCases where engineer != author {
                if message.body.contains("@\(engineer.rawValue)"),
                   participantIDs.contains(engineer) {
                    targets.append((engineer, "mention"))
                }
            }
            // A review request wakes its target.
            if message.kind == .review, let structured = message.structured,
               let value = try? JSONDecoder().decode(JSONValue.self,
                                                     from: Data(structured.utf8)),
               let reviewerRaw = value["reviewer"]?.stringValue,
               let reviewer = EngineerID(rawValue: reviewerRaw),
               reviewer != author, participantIDs.contains(reviewer),
               !targets.contains(where: { $0.0 == reviewer }) {
                targets.append((reviewer, "review_request"))
            }
        }

        for (engineer, reason) in targets {
            // Loop bound (T11): suppress after N consecutive engineer-triggered
            // wakeups without an intervening user message. User messages always go.
            if reason != "user_message",
               try repo.engineerWakeupsSinceLastUserMessage(message.taskID) >= wakeupLoopBound {
                try repo.insertWakeup(taskID: message.taskID, engineerID: engineer,
                                      reason: reason, triggerSeq: message.seq,
                                      state: "suppressed", at: timestamp)
                continue
            }
            try repo.insertWakeup(taskID: message.taskID, engineerID: engineer,
                                  reason: reason, triggerSeq: message.seq, at: timestamp)
        }
        // One system event per task when suppression kicks in.
        if targets.contains(where: { $0.1 != "user_message" }),
           try repo.engineerWakeupsSinceLastUserMessage(message.taskID) >= wakeupLoopBound,
           !(try repo.messages(message.taskID).contains {
               $0.body == "Discussion round limit reached; waiting for user" }) {
            try repo.insertMessage(Message(
                id: MessageID(newID("msg")), taskID: message.taskID,
                seq: try repo.nextMessageSeq(message.taskID), author: .system,
                kind: .systemEvent,
                body: "Discussion round limit reached; waiting for user",
                deliveryState: .committed, createdAt: timestamp, updatedAt: timestamp))
        }
    }

    private func scheduleWakeupCoalescer() {
        guard !wakeupScheduled, !isShutdown else { return }
        wakeupScheduled = true
        Task { await self.runWakeupCoalescer() }
    }

    /// After the coalescing delay, run one turn per (task, engineer) covering all
    /// pending wakeup rows; in-flight pairs stay pending until the turn finishes.
    private func runWakeupCoalescer() async {
        if wakeupCoalescence > .zero {
            try? await Task.sleep(for: wakeupCoalescence)
        }
        defer { wakeupScheduled = false }
        while !isShutdown {
            guard let pending = attempt("pendingWakeups", { try repo.pendingWakeups() }),
                  !pending.isEmpty else { break }
            var groups: [String: (taskID: TaskID, engineer: EngineerID,
                                 reason: String, rows: [Int64])] = [:]
            var order: [String] = []
            for row in pending {
                let key = row.taskID.rawValue + ":" + row.engineerID.rawValue
                if groups[key] == nil {
                    groups[key] = (row.taskID, row.engineerID, row.reason, [])
                    order.append(key)
                }
                groups[key]!.rows.append(row.id)
            }
            var anyPending = false
            for key in order {
                guard let group = groups[key] else { continue }
                if runningTurns.contains(key) { anyPending = true; continue }
                let task: WorkshopTask? = attempt("wakeupTask",
                                                  { try repo.task(group.taskID) }) ?? nil
                guard let adapter = adapters[group.engineer], let task else {
                    for id in group.rows {
                        _ = attempt("wakeupSuppressed",
                                    { try repo.setWakeupState(id, "suppressed",
                                                              at: now()) })
                    }
                    continue
                }
                let probe = await adapter.probe()
                guard probe.health.kind == .available else {
                    for id in group.rows {
                        _ = attempt("wakeupSuppressed",
                                    { try repo.setWakeupState(id, "suppressed",
                                                              at: now()) })
                    }
                    let timestamp = now()
                    _ = attempt("wakeupUnavailableEvent") {
                        try repo.insertMessage(Message(
                            id: MessageID(newID("msg")), taskID: task.id,
                            seq: try repo.nextMessageSeq(task.id), author: .system,
                            kind: .systemEvent,
                            body: "\(group.engineer.rawValue.capitalized) was "
                                + "mentioned but is \(probe.health.detail); not woken",
                            deliveryState: .committed, createdAt: timestamp,
                            updatedAt: timestamp))
                    }
                    continue
                }
                for id in group.rows {
                    _ = attempt("wakeupRunning",
                                { try repo.setWakeupState(id, "running", at: now()) })
                }
                let owned: Subtask? = attempt("wakeupSubtask", {
                    try repo.latestOwnedSubtask(taskID: task.id, owner: group.engineer)
                }) ?? nil
                let fallback: Subtask? = attempt("wakeupFallbackSubtask", {
                    try repo.subtasks(task.id).first
                }) ?? nil
                await runTurn(adapter: adapter, engineer: group.engineer, task: task,
                              subtask: owned ?? fallback,
                              wakeReason: group.reason)
                for id in group.rows {
                    _ = attempt("wakeupDone",
                                { try repo.setWakeupState(id, "done", at: now()) })
                }
            }
            // Another batch may have arrived while we ran turns; loop if so, else exit.
            if !anyPending {
                let more = attempt("pendingWakeups", { try repo.pendingWakeups() }) ?? []
                if more.isEmpty { break }
            }
        }
    }

    // MARK: - Recovery

    /// Mark messages left `streaming` by a previous process as committed + uncertain,
    /// and block the owning subtask/task for reconciliation.
    private func recoverInterruptedStreams() {
        guard let interrupted = attempt("streamingMessages", { try repo.streamingMessages() }),
              !interrupted.isEmpty else { return }
        let timestamp = now()
        for message in interrupted {
            _ = attempt("recoverInterruptedStream") {
                try repo.db.transaction {
                    try repo.updateMessageBody(
                        message.id,
                        body: message.body
                            + "\n\n[stream interrupted by service restart; marked uncertain]",
                        at: timestamp)
                    try repo.updateMessageDelivery(message.id, .committed, at: timestamp)
                    if let authorID = message.author.engineerID,
                       let subtask = try repo.latestOwnedSubtask(taskID: message.taskID,
                                                               owner: authorID) {
                        try repo.updateSubtaskState(subtask.id, .blocked, at: timestamp)
                    }
                    if let task = try repo.task(message.taskID), task.state == .working {
                        try transition(message.taskID, from: .working, to: .blocked,
                                       at: timestamp)
                    }
                    try repo.insertMessage(Message(
                        id: MessageID(newID("msg")), taskID: message.taskID,
                        seq: try repo.nextMessageSeq(message.taskID), author: .system,
                        kind: .systemEvent,
                        body: "Interrupted stream marked uncertain after service restart; "
                            + "task blocked pending reconciliation (Phase 4)",
                        deliveryState: .committed, createdAt: timestamp, updatedAt: timestamp))
                }
            }
        }
        publishCommitted()
    }

    // MARK: - Dispatcher

    private func scheduleDispatch() {
        guard dispatcherEnabled, !dispatcherScheduled, !isShutdown else { return }
        dispatcherScheduled = true
        Task { await self.dispatchLoop() }
    }

    private func dispatchLoop() async {
        while !isShutdown {
            guard let rows = attempt("pendingOutbox",
                                     { try repo.pendingOutbox(eventType: Self.dispatchRequested) }),
                  let row = rows.first else { break }
            if let failure = await handleDispatch(row) {
                let marked = attempt("markOutboxFailed") {
                    try repo.db.transaction {
                        try repo.markOutboxFailed(row.seq, reason: failure, at: now())
                    }
                }
                if marked == nil { break } // cannot mark — do not spin on the row
            }
        }
        dispatcherScheduled = false
    }

    /// Exposed for tests that drive the dispatcher manually.
    public func processPendingDispatches() async {
        await dispatchLoop()
    }

    /// Test hook: run the CAS claim directly (concurrent callers → exactly one winner).
    public func claimForTest(subtaskID: SubtaskID, owner: EngineerID,
                             expectedGeneration: Int) throws -> Bool {
        try repo.claimSubtask(subtaskID, owner: owner, expectedGeneration: expectedGeneration,
                              leaseExpiresAt: now().addingTimeInterval(300), at: now())
    }

    /// Test hook: simulate a crashed mid-turn state — claimed subtask, working task,
    /// and an uncommitted streaming message.
    public func insertStreamingMessageForTest() throws {
        guard let task = try repo.listTasks().first else { return }
        let timestamp = now()
        try repo.db.transaction {
            if let subtask = try repo.subtasks(task.id).first {
                _ = try repo.claimSubtask(subtask.id, owner: .devin,
                                          expectedGeneration: subtask.generation,
                                          leaseExpiresAt: timestamp.addingTimeInterval(300),
                                          at: timestamp)
            }
            var state = task.state
            for next in [TaskState.ready, .working] where state != next {
                try transition(task.id, from: state, to: next, at: timestamp)
                state = next
            }
            try repo.insertMessage(Message(
                id: MessageID(newID("msg")), taskID: task.id,
                seq: try repo.nextMessageSeq(task.id), author: .engineer(.devin),
                kind: .text, body: "partial reply", deliveryState: .streaming,
                createdAt: timestamp, updatedAt: timestamp))
        }
    }

    /// Test hook: insert a raw pending dispatch.requested row (e.g. a poisoned payload).
    public func insertOutboxForTest(eventType: String, taskID: TaskID?, payload: String) throws {
        _ = try repo.insertOutbox(taskID: taskID, eventType: eventType, payload: payload,
                                  deliveryState: "pending", at: now())
    }

    /// Returns nil on success, or a failure reason for the outbox row.
    private func handleDispatch(_ row: OutboxEvent) async -> String? {
        guard let payload = try? JSONDecoder().decode(JSONValue.self,
                                                      from: Data(row.payload.utf8)),
              let taskIDRaw = payload["task_id"]?.stringValue,
              let subtaskIDRaw = payload["subtask_id"]?.stringValue else {
            return "invalid dispatch payload"
        }
        let taskID = TaskID(taskIDRaw)
        let subtaskID = SubtaskID(subtaskIDRaw)
        let preferredOwner = payload["preferred_owner"]?.stringValue
            .flatMap(EngineerID.init(rawValue:))

        guard let taskOpt = attempt("task", { try repo.task(taskID) }), let task = taskOpt,
              let subOpt = attempt("subtask", { try repo.subtask(subtaskID) }),
              var subtask = subOpt else {
            return "task or subtask not found"
        }

        // Eligible engineers: participants whose probe reports available (spec §5.2).
        var order = EngineerID.allCases
        if let preferredOwner, let index = order.firstIndex(of: preferredOwner) {
            order.remove(at: index)
            order.insert(preferredOwner, at: 0)
        }
        let participantIDs = attempt("participants", { try repo.participants(taskID) })?
            .map(\.engineerID) ?? []
        var winner: EngineerID?
        for engineer in order where participantIDs.contains(engineer) {
            guard let adapter = adapters[engineer] else { continue }
            let probe = await adapter.probe()
            if probe.health.kind == .available {
                winner = engineer
                break
            }
        }

        guard let winner, let adapter = adapters[winner] else {
            // No eligible engineer: blocked, system event, no retry storm (T15-lite).
            let timestamp = now()
            let ok = attempt("noEligibleCommit") {
                try repo.db.transaction {
                    try transition(taskID, from: task.state, to: .ready, at: timestamp)
                    try transition(taskID, from: .ready, to: .working, at: timestamp)
                    try transition(taskID, from: .working, to: .blocked, at: timestamp)
                    try repo.insertMessage(Message(
                        id: MessageID(newID("msg")), taskID: taskID,
                        seq: try repo.nextMessageSeq(taskID), author: .system,
                        kind: .systemEvent, body: "No eligible engineer available",
                        deliveryState: .committed, createdAt: timestamp, updatedAt: timestamp))
                    try repo.insertOutbox(taskID: taskID, eventType: "task.state_changed",
                                          payload: #"{"task_id":""# + taskID.rawValue
                                              + #"","state":"blocked"}"#,
                                          deliveryState: "pending", at: timestamp)
                    try repo.markOutboxDelivered(row.seq, at: timestamp)
                }
            }
            publishCommitted()
            return ok == nil ? "no-eligible commit failed" : nil
        }

        // Atomic CAS claim; changes()==1 is the single winner (T04).
        let timestamp = now()
        let lease = timestamp.addingTimeInterval(300)
        var claimed = false
        let ok = attempt("claimCommit") {
            try repo.db.transaction {
                claimed = try repo.claimSubtask(subtaskID, owner: winner,
                                              expectedGeneration: subtask.generation,
                                              leaseExpiresAt: lease, at: timestamp)
                guard claimed else { return }
                try repo.markOutboxDelivered(row.seq, at: timestamp)
                try transition(taskID, from: task.state, to: .ready, at: timestamp)
                try transition(taskID, from: .ready, to: .working, at: timestamp)
                try repo.insertMessage(Message(
                    id: MessageID(newID("msg")), taskID: taskID,
                    seq: try repo.nextMessageSeq(taskID), author: .system, kind: .systemEvent,
                    body: "\(winner.displayName) claimed \(subtask.title) (generation \(subtask.generation + 1))",
                    deliveryState: .committed, createdAt: timestamp, updatedAt: timestamp))
                try repo.insertOutbox(taskID: taskID, eventType: "subtask.claimed",
                                      payload: #"{"subtask_id":""# + subtaskID.rawValue
                                          + #"","owner":""# + winner.rawValue
                                          + #"","generation":\#(subtask.generation + 1)}"#,
                                      deliveryState: "pending", at: timestamp)
            }
        }
        publishCommitted()
        guard ok != nil else { return "claim transaction failed" }
        guard claimed else { return "claim lost or subtask already owned" }

        if let reloaded: Subtask? = attempt("subtaskReload", { try repo.subtask(subtaskID) }),
           let reloaded {
            subtask = reloaded
        }

        // Run the turn outside the claim transaction.
        inflightTurns += 1
        defer { inflightTurns -= 1 }
        await runTurn(adapter: adapter, engineer: winner, task: task, subtask: subtask,
                      wakeReason: nil)
        return nil
    }

    /// Transition helper: verifies the §8.2 edge, no-op when already at `to`.
    private func transition(_ taskID: TaskID, from: TaskState, to: TaskState, at timestamp: Date) throws {
        if from == to { return }
        guard from.canTransition(to: to) else {
            throw WorkshopError.illegalTransition(from: from, to: to)
        }
        try repo.updateTaskState(taskID, to, at: timestamp)
    }

    /// Payload of a task.state_changed outbox event; usage nulls stay null.
    private struct StateChangedPayload: Codable {
        var task_id: String
        var state: String
        var usage: UsageSample?
    }

    /// Run one adapter turn. `wakeReason == nil` is the owner-execution turn
    /// (subtask → review, task → verifying on success); non-nil is a discussion
    /// wakeup turn which only commits a reply message.
    private func runTurn(adapter: EngineerAdapter, engineer: EngineerID,
                         task: WorkshopTask, subtask: Subtask?,
                         wakeReason: String?) async {
        let turnKey = task.id.rawValue + ":" + engineer.rawValue
        runningTurns.insert(turnKey)
        defer { runningTurns.remove(turnKey) }

        let timestamp = now()
        let binding = SessionBinding(taskID: task.id, engineerID: engineer, role: "owner",
                                     workerID: "main")
        // Reuse a persisted native session binding when present (§6.2).
        var bound = binding
        if let stored: WorkshopRepository.SessionBindingRecord =
            attempt("sessionBinding", {
                try repo.sessionBinding(taskID: task.id, engineerID: engineer,
                                        role: "owner", workerID: "main")
            }) ?? nil {
            bound.nativeSessionID = stored.nativeSessionID
            bound.modelSelection = stored.modelSelection
            bound.recoveryState = stored.recoveryState
        }
        let ref: SessionRef
        do {
            ref = try await adapter.openTaskSession(binding: bound)
            if ref.nativeSessionID != bound.nativeSessionID {
                bound.nativeSessionID = ref.nativeSessionID
                bound.recoveryState = "bound"
                _ = attempt("saveSessionBinding") {
                    try repo.saveSessionBinding(.init(
                        taskID: bound.taskID, engineerID: bound.engineerID,
                        role: bound.role, workerID: bound.workerID,
                        nativeSessionID: bound.nativeSessionID,
                        profileRevision: bound.profileRevision,
                        modelSelection: bound.modelSelection,
                        recoveryState: bound.recoveryState))
                }
            }
        } catch {
            log.error("openTaskSession failed for \(engineer.rawValue, privacy: .public): \(error.localizedDescription, privacy: .public)")
            _ = attempt("openFailedEvent") {
                try repo.insertMessage(Message(
                    id: MessageID(newID("msg")), taskID: task.id,
                    seq: try repo.nextMessageSeq(task.id), author: .system,
                    kind: .systemEvent,
                    body: "Turn could not start for \(engineer.displayName): "
                        + error.localizedDescription,
                    deliveryState: .committed, createdAt: timestamp,
                    updatedAt: timestamp))
            }
            return
        }

        // Streaming placeholder message in its own transaction.
        let messageID = MessageID(newID("msg"))
        _ = attempt("insertStreamingMessage") {
            try repo.db.transaction {
                try repo.insertMessage(Message(
                    id: messageID, taskID: task.id, seq: try repo.nextMessageSeq(task.id),
                    author: .engineer(engineer), kind: .text, body: "",
                    deliveryState: .streaming, createdAt: timestamp, updatedAt: timestamp))
            }
        }

        // Context: only messages after the participant's consumed cursor (§8.5),
        // bounded to the last 60.
        let lastRead: Int64 = attempt("participantCursor", {
            try repo.participant(task.id, engineer)?.lastReadSeq ?? 0
        }) ?? 0
        var recent: [Message] = attempt("recentMessages",
                                        { try repo.messages(task.id, afterSeq: lastRead) }) ?? []
        var truncatedNote: String?
        if recent.count > 60 {
            truncatedNote = "\(recent.count - 60) older messages omitted"
            recent = Array(recent.suffix(60))
        }
        let maxSeq = recent.map(\.seq).max() ?? lastRead

        var body = ""
        var usage = UsageSample(source: "unknown")
        var failedReason: String?
        var sawCompletion = false
        let context = TurnContext(task: task, subtask: subtask,
                                  recentMessages: recent,
                                  wakeReason: wakeReason,
                                  truncatedNote: truncatedNote)
        packetInspector?(engineer, context.packetText(for: engineer))
        let turnID = newID("turn")
        let stream = adapter.sendTurn(ref: ref, turnID: turnID, context: context,
                                      deadline: timestamp.addingTimeInterval(300))
        do {
            for try await event in stream {
                switch event {
                case .messageDelta(let delta):
                    body += delta
                    _ = attempt("updateMessageBody",
                                { try repo.updateMessageBody(messageID, body: body, at: now()) })
                    publishTransient(taskID: task.id, type: "message.delta",
                                     payload: #"{"message_id":""# + messageID.rawValue
                                         + #"","task_id":""# + task.id.rawValue + #""}"#)
                case .usageSample(let input, let output, let cacheRead, let cacheWrite, let source):
                    usage = UsageSample(input: input, output: output, cacheRead: cacheRead,
                                        cacheWrite: cacheWrite, source: source)
                    _ = attempt("usageSample") {
                        try repo.insertUsageSample(taskID: task.id, engineerID: engineer,
                                                   provider: engineer.rawValue,
                                                   model: bound.modelSelection,
                                                   nativeSessionID: ref.nativeSessionID,
                                                   turnID: turnID, sample: usage, at: now())
                    }
                case .uncertain(let note):
                    _ = attempt("uncertainNote") {
                        let t = now()
                        try repo.insertMessage(Message(
                            id: MessageID(newID("msg")), taskID: task.id,
                            seq: try repo.nextMessageSeq(task.id), author: .system,
                            kind: .systemEvent, body: note,
                            deliveryState: .committed, createdAt: t, updatedAt: t))
                    }
                case .turnCompleted:
                    sawCompletion = true
                default:
                    break
                }
            }
        } catch {
            failedReason = error.localizedDescription
            body += "\n\n[turn failed: \(failedReason!); marked uncertain]"
        }

        // Commit the turn outcome. A failed stream never reports completion.
        // Consumed cursor advances only on a completed turn (§8.5).
        let endTime = now()
        _ = attempt("commitTurn") {
            try repo.db.transaction {
                try repo.updateMessageBody(messageID, body: body, at: endTime)
                try repo.updateMessageDelivery(messageID, .committed, at: endTime)
                try repo.insertOutbox(taskID: task.id, eventType: "message.committed",
                                      payload: #"{"message_id":""# + messageID.rawValue
                                          + #"","task_id":""# + task.id.rawValue + #""}"#,
                                      deliveryState: "pending", at: endTime)
                if failedReason == nil, sawCompletion {
                    try repo.setLastReadSeq(task.id, engineer, seq: maxSeq, at: endTime)
                }
                if let failedReason {
                    if wakeReason == nil {
                        if let subtask {
                            try repo.updateSubtaskState(subtask.id, .blocked, at: endTime)
                        }
                        if let current = try repo.task(task.id), current.state == .working {
                            try transition(task.id, from: .working, to: .blocked, at: endTime)
                        }
                        try repo.insertMessage(Message(
                            id: MessageID(newID("msg")), taskID: task.id,
                            seq: try repo.nextMessageSeq(task.id), author: .system,
                            kind: .systemEvent,
                            body: "Turn failed: \(failedReason). Result uncertain; "
                                + "awaiting reconciliation.",
                            deliveryState: .committed, createdAt: endTime, updatedAt: endTime))
                        let payload = try JSONEncoder().encode(StateChangedPayload(
                            task_id: task.id.rawValue, state: "blocked", usage: usage))
                        try repo.insertOutbox(taskID: task.id, eventType: "task.state_changed",
                                              payload: String(decoding: payload, as: UTF8.self),
                                              deliveryState: "pending", at: endTime)
                    }
                } else if wakeReason == nil {
                    if let subtask {
                        try repo.updateSubtaskState(subtask.id, .review, at: endTime)
                    }
                    if let current = try repo.task(task.id) {
                        try transition(task.id, from: current.state, to: .verifying, at: endTime)
                    }
                    try repo.insertMessage(Message(
                        id: MessageID(newID("msg")), taskID: task.id,
                        seq: try repo.nextMessageSeq(task.id), author: .system,
                        kind: .systemEvent,
                        body: "Owner reported complete; verification pending",
                        deliveryState: .committed, createdAt: endTime, updatedAt: endTime))
                    let payload = try JSONEncoder().encode(StateChangedPayload(
                        task_id: task.id.rawValue, state: "verifying", usage: usage))
                    try repo.insertOutbox(taskID: task.id, eventType: "task.state_changed",
                                          payload: String(decoding: payload, as: UTF8.self),
                                          deliveryState: "pending", at: endTime)
                }
            }
        }
        publishCommitted()
    }
}
